blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/marty-martini/raycast-prompt-pocket/discussions
    about: Ask questions and discuss with the community

